-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/cleaning-sop.manual.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('83fe944a-e45c-59f4-b7c3-047105c8bac2'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Cleaning Job', '{"titleKey":"jobTitle","primaryKey":"id","properties":{"jobTitle":{"type":"string","required":true,"displayName":"Job Title"},"customerName":{"type":"string","required":true,"displayName":"Customer Name"},"siteAddress":{"type":"string","required":true,"displayName":"Site Address"},"scheduledDate":{"type":"date","required":true,"displayName":"Scheduled Date"},"checklistCompleted":{"type":"boolean","required":false,"displayName":"Checklist Completed"},"qaNotes":{"type":"string","required":false,"displayName":"QA Notes"},"status":{"type":"string","required":true,"displayName":"Status","picklistConfig":{"allowMultiple":false,"defaultValue":"Assigned","options":["Assigned","En Route","On Site","Cleaning","QA Check","Completed"]}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('54460de0-acb8-5425-8665-78272b7c5b9a'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Staff Member', '{"titleKey":"fullName","primaryKey":"id","properties":{"fullName":{"type":"string","required":true,"displayName":"Full Name"},"phone":{"type":"string","required":false,"displayName":"Phone"},"role":{"type":"string","required":false,"displayName":"Role","picklistConfig":{"allowMultiple":false,"options":["Cleaner","Supervisor","QA"]}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '8cda30c0-09f5-5b62-8178-59aaa47daa28'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Job Staff Assignment', 'ONE_TO_MANY',
  '83fe944a-e45c-59f4-b7c3-047105c8bac2'::uuid, '54460de0-acb8-5425-8665-78272b7c5b9a'::uuid,
  'Cleaning Job', 'Staff Member',
  NULL, NULL, NULL, 'assignedStaff', '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('f3558a7b-40c1-5d99-8406-00b4892655f1'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Travel', '{"executionType":"declarative","parameters":[{"name":"job","type":"object-reference","required":true,"displayName":"Cleaning Job","objectTypeId":"83fe944a-e45c-59f4-b7c3-047105c8bac2"}],"rules":[{"type":"modify_object","objectParameter":"job","properties":{"status":{"source":"static","value":"En Route"}}}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"job","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Assigned"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('c2de47af-1d03-55a6-809e-3c6fcb4c2c28'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Check In On Site', '{"executionType":"declarative","parameters":[{"name":"job","type":"object-reference","required":true,"displayName":"Cleaning Job","objectTypeId":"83fe944a-e45c-59f4-b7c3-047105c8bac2"}],"rules":[{"type":"modify_object","objectParameter":"job","properties":{"status":{"source":"static","value":"On Site"}}}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"job","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"En Route"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('2c06a3c4-44d6-57a0-b733-05e5d6171153'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Cleaning', '{"executionType":"declarative","parameters":[{"name":"job","type":"object-reference","required":true,"displayName":"Cleaning Job","objectTypeId":"83fe944a-e45c-59f4-b7c3-047105c8bac2"}],"rules":[{"type":"modify_object","objectParameter":"job","properties":{"status":{"source":"static","value":"Cleaning"}}}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"job","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"On Site"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('eff568f5-af28-580c-94cf-1b0786f87c88'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Submit For QA', '{"executionType":"declarative","parameters":[{"name":"job","type":"object-reference","required":true,"displayName":"Cleaning Job","objectTypeId":"83fe944a-e45c-59f4-b7c3-047105c8bac2"}],"rules":[{"type":"modify_object","objectParameter":"job","properties":{"status":{"source":"static","value":"QA Check"},"checklistCompleted":{"source":"static","value":true}}}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"job","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Cleaning"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('1ee23f05-acd6-55eb-b10c-797c21bda09c'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Mark Completed', '{"executionType":"declarative","parameters":[{"name":"job","type":"object-reference","required":true,"displayName":"Cleaning Job","objectTypeId":"83fe944a-e45c-59f4-b7c3-047105c8bac2"}],"rules":[{"type":"modify_object","objectParameter":"job","properties":{"status":{"source":"static","value":"Completed"}}}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"job","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"QA Check"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('e5d468d0-4333-54cd-b84f-f7ded448e552'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Reopen Job', '{"executionType":"declarative","parameters":[{"name":"job","type":"object-reference","required":true,"displayName":"Cleaning Job","objectTypeId":"83fe944a-e45c-59f4-b7c3-047105c8bac2"}],"rules":[{"type":"modify_object","objectParameter":"job","properties":{"status":{"source":"static","value":"Cleaning"}}}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"job","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"QA Check"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '36d56020-8852-50b5-8641-0dd3725f5b87'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Cleaning SOP Workflow',
  ARRAY['83fe944a-e45c-59f4-b7c3-047105c8bac2'::uuid]::uuid[], ARRAY['status']::text[], '{"version":1,"nodes":[],"edges":[]}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

