-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/deal-pipeline.default.export.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('e5cf5e27-a6f7-585d-a9a5-e645ffad117a'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Company', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"type":"string","required":true,"displayName":"Company Name"},"industry":{"type":"string","required":false,"displayName":"Industry"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('8fcb7a2d-03cb-5abb-bdc5-cb21757caacc'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Contact', '{"titleKey":"fullName","primaryKey":"id","properties":{"email":{"type":"string","required":false,"displayName":"Email"},"fullName":{"type":"string","required":true,"displayName":"Full Name"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"type":"string","required":true,"displayName":"Deal Name"},"amount":{"type":"number","required":false,"validation":{"min":0},"displayName":"Amount"},"status":{"type":"string","required":true,"displayName":"Status","picklistConfig":{"options":["Lead","Qualified","Proposal","Negotiation","Won","Lost"],"defaultValue":"Lead","allowMultiple":false}},"nextStep":{"type":"string","required":false,"displayName":"Next Step"},"priority":{"type":"string","required":false,"displayName":"Priority","picklistConfig":{"options":["Low","Medium","High"],"defaultValue":"Medium","allowMultiple":false}},"closeReason":{"type":"string","required":false,"displayName":"Close Reason"},"probability":{"type":"number","required":false,"validation":{"max":100,"min":0},"displayName":"Probability"},"lastActivityAt":{"type":"timestamp","required":false,"displayName":"Last Activity At"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('24c7358c-477a-5410-92a3-0347fe869dea'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Contact Link', '{"titleKey":"role","isJunction":true,"primaryKey":"id","properties":{"role":{"type":"string","required":true,"displayName":"Role","picklistConfig":{"options":["Decision Maker","Champion","Influencer"],"allowMultiple":false}},"dealId":{"type":"object-reference","required":true,"displayName":"Deal","referenceConfig":{"targetObjectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"}},"contactId":{"type":"object-reference","required":true,"displayName":"Contact","referenceConfig":{"targetObjectTypeId":"8fcb7a2d-03cb-5abb-bdc5-cb21757caacc"}},"isPrimaryDecisionMaker":{"type":"boolean","required":false,"displayName":"Primary Decision Maker"}},"junctionMetadata":{"relationshipId":"e36fb120-f724-53f9-867c-7311154ff400","sourceObjectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8","targetObjectTypeId":"8fcb7a2d-03cb-5abb-bdc5-cb21757caacc"}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '1f0f72c7-a9e5-51d4-b614-23f20ff3c7c6'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Company has Deals', 'ONE_TO_MANY',
  'e5cf5e27-a6f7-585d-a9a5-e645ffad117a'::uuid, '67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid,
  'company', 'deals',
  NULL, NULL, NULL, 'companyId', '{"notes":"Each deal belongs to one company"}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  'e36fb120-f724-53f9-867c-7311154ff400'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Contacts', 'MANY_TO_MANY',
  '67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid, '8fcb7a2d-03cb-5abb-bdc5-cb21757caacc'::uuid,
  'deal', 'contacts',
  '24c7358c-477a-5410-92a3-0347fe869dea'::uuid, NULL, NULL, NULL, '{"notes":"Backed by junction entity with role metadata"}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('7298e6e0-f0a8-5dc6-be98-8472f7f44c30'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Close Lost', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"Lost","source":"static"},"closeReason":{"source":"parameter","parameterName":"lossReason"},"probability":{"value":0,"source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"lossReason","type":"string","required":true,"displayName":"Loss Reason"}],"description":"Transitions Deal from \"Negotiation\" to \"Lost\" with additional business updates","executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Negotiation"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('17c0803e-e218-58ec-8af0-2455adfa02dc'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Close Won', '{"rules":[{"type":"modify_object","properties":{"amount":{"source":"parameter","parameterName":"finalAmount"},"status":{"value":"Won","source":"static"},"nextStep":{"value":"Onboard customer","source":"static"},"probability":{"value":100,"source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"finalAmount","type":"number","required":true,"displayName":"Final Amount"}],"description":"Transitions Deal from \"Negotiation\" to \"Won\" with additional business updates","executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Negotiation"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('d1eeb49b-8355-5d99-9913-5479a59d206c'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Create Proposal', '{"rules":[{"type":"modify_object","properties":{"amount":{"source":"parameter","parameterName":"proposedAmount"},"status":{"value":"Proposal","source":"static"},"nextStep":{"source":"parameter","parameterName":"proposalSummary"},"probability":{"value":50,"source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"proposedAmount","type":"number","required":true,"displayName":"Proposed Amount"},{"name":"proposalSummary","type":"string","required":true,"displayName":"Proposal Summary"}],"description":"Transitions Deal from \"Qualified\" to \"Proposal\" with additional business updates","executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Qualified"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('29c57b4b-929d-586b-a673-70aa869592da'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Link Contact To Deal', '{"rules":[{"type":"create_object","properties":{"role":{"source":"parameter","parameterName":"role"},"dealId":{"source":"parameter","parameterName":"deal"},"contactId":{"source":"parameter","parameterName":"contact"},"isPrimaryDecisionMaker":{"source":"parameter","parameterName":"isPrimaryDecisionMaker"}},"objectTypeId":"24c7358c-477a-5410-92a3-0347fe869dea"},{"type":"modify_object","properties":{"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"contact","type":"object-reference","required":true,"displayName":"Contact","objectTypeId":"8fcb7a2d-03cb-5abb-bdc5-cb21757caacc"},{"name":"role","type":"string","required":true,"displayName":"Role","picklistConfig":{"options":["Decision Maker","Champion","Influencer"],"allowMultiple":false}},{"name":"isPrimaryDecisionMaker","type":"boolean","required":false,"displayName":"Primary Decision Maker"}],"description":"Create a deal-contact link row with relationship metadata","executionType":"declarative","submissionCriteria":[{"type":"logical","operator":"OR","expressions":[{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Qualified"},"operator":"="},{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Proposal"},"operator":"="},{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Negotiation"},"operator":"="}]}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('ba5870f6-4163-53e0-9fbe-5004c9717cae'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Log Follow-up Note', '{"rules":[{"type":"modify_object","properties":{"nextStep":{"source":"parameter","parameterName":"note"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"note","type":"string","required":true,"displayName":"Follow-up Note"}],"description":"Adds next-step note and updates activity timestamp without stage transition","executionType":"declarative"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('f006b98d-83a4-57a6-a1ef-210edf73a569'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Qualify Deal', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"Qualified","source":"static"},"nextStep":{"source":"parameter","parameterName":"discoveryNotes"},"priority":{"source":"parameter","parameterName":"priority"},"probability":{"value":25,"source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"discoveryNotes","type":"string","required":true,"displayName":"Discovery Notes"},{"name":"priority","type":"string","required":false,"displayName":"Priority","picklistConfig":{"options":["Low","Medium","High"],"allowMultiple":false}}],"description":"Transitions Deal from \"Lead\" to \"Qualified\" with additional business updates","executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Lead"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('cbdafe79-0acf-5579-b5d6-2607c4cab618'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Negotiation', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"Negotiation","source":"static"},"nextStep":{"source":"parameter","parameterName":"negotiationPlan"},"probability":{"value":70,"source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"deal"}],"parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"negotiationPlan","type":"string","required":true,"displayName":"Negotiation Plan"}],"description":"Transitions Deal from \"Proposal\" to \"Negotiation\" with additional business updates","executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"deal","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Proposal"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '51edc504-0b31-5099-9d04-9d0c85bb6d80'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Pipeline',
  ARRAY['67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid]::uuid[], ARRAY['status']::text[], '{"edges":[],"nodes":[],"version":1}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

