-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/generated.agent.kanban.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Deal Name","type":"string","required":true},"status":{"displayName":"Status","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["Lead","Qualified","Proposal","Negotiation","Won","Lost"],"defaultValue":"Lead"}},"amount":{"displayName":"Amount","type":"number","required":false,"validation":{"min":0}},"nextStep":{"displayName":"Next Step","type":"string","required":false},"probability":{"displayName":"Probability","type":"number","required":false,"validation":{"min":0,"max":100}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('e5cf5e27-a6f7-585d-a9a5-e645ffad117a'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Company', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Company Name","type":"string","required":true}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('8fcb7a2d-03cb-5abb-bdc5-cb21757caacc'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Contact', '{"titleKey":"fullName","primaryKey":"id","properties":{"fullName":{"displayName":"Full Name","type":"string","required":true},"email":{"displayName":"Email","type":"string","required":false}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('24c7358c-477a-5410-92a3-0347fe869dea'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Contact Link', '{"titleKey":"role","primaryKey":"id","isJunction":true,"junctionMetadata":{"relationshipId":"e36fb120-f724-53f9-867c-7311154ff400","sourceObjectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8","targetObjectTypeId":"8fcb7a2d-03cb-5abb-bdc5-cb21757caacc"},"properties":{"dealId":{"displayName":"Deal","type":"object-reference","required":true,"referenceConfig":{"targetObjectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"}},"contactId":{"displayName":"Contact","type":"object-reference","required":true,"referenceConfig":{"targetObjectTypeId":"8fcb7a2d-03cb-5abb-bdc5-cb21757caacc"}},"role":{"displayName":"Role","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["Decision Maker","Champion","Influencer"]}},"brokerName":{"displayName":"Broker Name","type":"string","required":false},"connectedAt":{"displayName":"Connected At","type":"timestamp","required":false}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '6e6fc43d-508b-5112-b595-4eee7aae9e18'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Company has Deals', 'ONE_TO_MANY',
  'e5cf5e27-a6f7-585d-a9a5-e645ffad117a'::uuid, '67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid,
  'company', 'deals',
  NULL, NULL, NULL, 'companyId', '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  'e36fb120-f724-53f9-867c-7311154ff400'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Contacts', 'MANY_TO_MANY',
  '67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid, '8fcb7a2d-03cb-5abb-bdc5-cb21757caacc'::uuid,
  'deal', 'contacts',
  '24c7358c-477a-5410-92a3-0347fe869dea'::uuid, NULL, NULL, NULL, '{"notes":"Backed relationship with business metadata"}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('f006b98d-83a4-57a6-a1ef-210edf73a569'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Qualify Deal', '{"executionType":"declarative","description":"Transitions Deal from Lead to Qualified","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"discoveryNotes","type":"string","displayName":"Discovery Notes","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Lead"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Qualified"},"nextStep":{"source":"parameter","parameterName":"discoveryNotes"},"probability":{"source":"static","value":25}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('d1eeb49b-8355-5d99-9913-5479a59d206c'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Create Proposal', '{"executionType":"declarative","description":"Transitions Deal from Qualified to Proposal","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"proposedAmount","type":"number","displayName":"Proposed Amount","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Qualified"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Proposal"},"amount":{"source":"parameter","parameterName":"proposedAmount"},"probability":{"source":"static","value":50}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('cbdafe79-0acf-5579-b5d6-2607c4cab618'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Negotiation', '{"executionType":"declarative","description":"Transitions Deal from Proposal to Negotiation","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"negotiationPlan","type":"string","displayName":"Negotiation Plan","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Proposal"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Negotiation"},"nextStep":{"source":"parameter","parameterName":"negotiationPlan"},"probability":{"source":"static","value":70}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('17c0803e-e218-58ec-8af0-2455adfa02dc'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Close Won', '{"executionType":"declarative","description":"Transitions Deal from Negotiation to Won","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"finalAmount","type":"number","displayName":"Final Amount","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Negotiation"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Won"},"amount":{"source":"parameter","parameterName":"finalAmount"},"probability":{"source":"static","value":100}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('7298e6e0-f0a8-5dc6-be98-8472f7f44c30'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Close Lost', '{"executionType":"declarative","description":"Transitions Deal from Negotiation to Lost","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"lossReason","type":"string","displayName":"Loss Reason","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Negotiation"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Lost"},"closeReason":{"source":"parameter","parameterName":"lossReason"},"probability":{"source":"static","value":0}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('29c57b4b-929d-586b-a673-70aa869592da'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Link Contact To Deal', '{"executionType":"declarative","description":"Creates backed relationship row with role, brokerName, connectedAt","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"},{"name":"contact","type":"object-reference","displayName":"Contact","required":true,"objectTypeId":"8fcb7a2d-03cb-5abb-bdc5-cb21757caacc"},{"name":"role","type":"string","displayName":"Role","required":true,"picklistConfig":{"allowMultiple":false,"options":["Decision Maker","Champion","Influencer"]}},{"name":"brokerName","type":"string","displayName":"Broker Name","required":false}],"submissionCriteria":[{"type":"logical","operator":"OR","expressions":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Qualified"}},{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Proposal"}},{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Negotiation"}}]}],"rules":[{"type":"create_object","objectTypeId":"24c7358c-477a-5410-92a3-0347fe869dea","properties":{"dealId":{"source":"parameter","parameterName":"deal"},"contactId":{"source":"parameter","parameterName":"contact"},"role":{"source":"parameter","parameterName":"role"},"brokerName":{"source":"parameter","parameterName":"brokerName"},"connectedAt":{"source":"current_timestamp"}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  'd8d645ff-f722-5c1d-b5ff-3eeea5fc3117'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Pipeline',
  ARRAY['67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid]::uuid[], ARRAY['status']::text[], '{"version":1,"nodes":[],"edges":[]}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

