-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/generated.agent.demo.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000025'::uuid, 'Demo Tenant', 'demo')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('89b89cb2-99b0-507f-b638-2bb8f801cf07'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Deal', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Deal Name","type":"string","required":true},"status":{"displayName":"Status","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["Lead","Qualified","Proposal","Negotiation","Won","Lost"],"defaultValue":"Lead"}},"amount":{"displayName":"Amount","type":"number","required":false,"validation":{"min":0}},"nextStep":{"displayName":"Next Step","type":"string","required":false},"probability":{"displayName":"Probability","type":"number","required":false,"validation":{"min":0,"max":100}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('8c3accd7-b377-5dc2-909a-81e6f297bca8'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Company', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Company Name","type":"string","required":true}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('085f3510-d3b5-5a7f-83f2-fc1bfea1078b'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Contact', '{"titleKey":"fullName","primaryKey":"id","properties":{"fullName":{"displayName":"Full Name","type":"string","required":true},"email":{"displayName":"Email","type":"string","required":false}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('4a8d810e-270c-5535-b341-70ef0a22b5a2'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Deal Contact Link', '{"titleKey":"role","primaryKey":"id","isJunction":true,"junctionMetadata":{"relationshipId":"dcb618e4-b383-5b71-9c9a-a109cb64e496","sourceObjectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07","targetObjectTypeId":"085f3510-d3b5-5a7f-83f2-fc1bfea1078b"},"properties":{"dealId":{"displayName":"Deal","type":"object-reference","required":true,"referenceConfig":{"targetObjectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"}},"contactId":{"displayName":"Contact","type":"object-reference","required":true,"referenceConfig":{"targetObjectTypeId":"085f3510-d3b5-5a7f-83f2-fc1bfea1078b"}},"role":{"displayName":"Role","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["Decision Maker","Champion","Influencer"]}},"brokerName":{"displayName":"Broker Name","type":"string","required":false},"connectedAt":{"displayName":"Connected At","type":"timestamp","required":false}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '78695ce3-454a-5801-b414-34e2450920fd'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Company has Deals', 'ONE_TO_MANY',
  '8c3accd7-b377-5dc2-909a-81e6f297bca8'::uuid, '89b89cb2-99b0-507f-b638-2bb8f801cf07'::uuid,
  'company', 'deals',
  NULL, NULL, NULL, 'companyId', '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  'dcb618e4-b383-5b71-9c9a-a109cb64e496'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Deal Contacts', 'MANY_TO_MANY',
  '89b89cb2-99b0-507f-b638-2bb8f801cf07'::uuid, '085f3510-d3b5-5a7f-83f2-fc1bfea1078b'::uuid,
  'deal', 'contacts',
  '4a8d810e-270c-5535-b341-70ef0a22b5a2'::uuid, NULL, NULL, NULL, '{"notes":"Backed relationship with business metadata"}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('f03f3c07-17b7-5676-9eca-2128c8615f07'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Qualify Deal', '{"executionType":"declarative","description":"Transitions Deal from Lead to Qualified","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"},{"name":"discoveryNotes","type":"string","displayName":"Discovery Notes","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Lead"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Qualified"},"nextStep":{"source":"parameter","parameterName":"discoveryNotes"},"probability":{"source":"static","value":25}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('f6d8ec65-b169-5087-9de6-4b28dc31f342'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Create Proposal', '{"executionType":"declarative","description":"Transitions Deal from Qualified to Proposal","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"},{"name":"proposedAmount","type":"number","displayName":"Proposed Amount","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Qualified"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Proposal"},"amount":{"source":"parameter","parameterName":"proposedAmount"},"probability":{"source":"static","value":50}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('902f3dcf-1a62-5670-b7e0-df859db53be9'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Start Negotiation', '{"executionType":"declarative","description":"Transitions Deal from Proposal to Negotiation","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"},{"name":"negotiationPlan","type":"string","displayName":"Negotiation Plan","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Proposal"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Negotiation"},"nextStep":{"source":"parameter","parameterName":"negotiationPlan"},"probability":{"source":"static","value":70}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('d1ad225f-c212-533f-be76-e468fc4f3960'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Close Won', '{"executionType":"declarative","description":"Transitions Deal from Negotiation to Won","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"},{"name":"finalAmount","type":"number","displayName":"Final Amount","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Negotiation"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Won"},"amount":{"source":"parameter","parameterName":"finalAmount"},"probability":{"source":"static","value":100}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('7d2afc4b-f023-57e0-a434-0b8bd1b087e7'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Close Lost', '{"executionType":"declarative","description":"Transitions Deal from Negotiation to Lost","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"},{"name":"lossReason","type":"string","displayName":"Loss Reason","required":true}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Negotiation"}}],"rules":[{"type":"modify_object","objectParameter":"deal","properties":{"status":{"source":"static","value":"Lost"},"closeReason":{"source":"parameter","parameterName":"lossReason"},"probability":{"source":"static","value":0}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('35635491-2800-51ed-a5ec-d87e326f8057'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Link Contact To Deal', '{"executionType":"declarative","description":"Creates backed relationship row with role, brokerName, connectedAt","parameters":[{"name":"deal","type":"object-reference","displayName":"Deal","required":true,"objectTypeId":"89b89cb2-99b0-507f-b638-2bb8f801cf07"},{"name":"contact","type":"object-reference","displayName":"Contact","required":true,"objectTypeId":"085f3510-d3b5-5a7f-83f2-fc1bfea1078b"},{"name":"role","type":"string","displayName":"Role","required":true,"picklistConfig":{"allowMultiple":false,"options":["Decision Maker","Champion","Influencer"]}},{"name":"brokerName","type":"string","displayName":"Broker Name","required":false}],"submissionCriteria":[{"type":"logical","operator":"OR","expressions":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Qualified"}},{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Proposal"}},{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Negotiation"}}]}],"rules":[{"type":"create_object","objectTypeId":"4a8d810e-270c-5535-b341-70ef0a22b5a2","properties":{"dealId":{"source":"parameter","parameterName":"deal"},"contactId":{"source":"parameter","parameterName":"contact"},"role":{"source":"parameter","parameterName":"role"},"brokerName":{"source":"parameter","parameterName":"brokerName"},"connectedAt":{"source":"current_timestamp"}}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  'da08de15-ecb6-5403-8ae9-64f038791884'::uuid, '00000000-0000-0000-0000-000000000025'::uuid, 'Deal Pipeline',
  ARRAY['89b89cb2-99b0-507f-b638-2bb8f801cf07'::uuid]::uuid[], ARRAY['status']::text[], '{"version":1,"nodes":[],"edges":[]}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

