-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/issue-workflow.oneshot.unstructured.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('77947897-ec67-5a36-ab7f-72bd34210d1b'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Issue', '{"titleKey":"title","primaryKey":"id","properties":{"status":{"displayName":"Status","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["To Do","Doing","Done"]}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('7d32e390-1d46-526d-96ae-b0d1d910a0c5'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Issue Comments', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Name","type":"string","required":true}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('2ebc3122-8d75-5fe1-86e1-91895cd5887b'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Comment', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Name","type":"string","required":true}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('4772417a-0805-5a1d-beab-fb4bae043265'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Work', '{"executionType":"declarative","parameters":[{"name":"issue","type":"object-reference","required":true,"displayName":"Issue","objectTypeId":"77947897-ec67-5a36-ab7f-72bd34210d1b"}],"rules":[{"type":"modify_object","properties":{"status":{"value":"Doing","source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"issue"}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"issue","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"To Do"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('770bcf64-d1f2-5d13-811f-6ff446f71ad6'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Mark as Done', '{"executionType":"declarative","parameters":[{"name":"issue","type":"object-reference","required":true,"displayName":"Issue","objectTypeId":"77947897-ec67-5a36-ab7f-72bd34210d1b"}],"rules":[{"type":"modify_object","properties":{"status":{"value":"Done","source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"issue"}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"issue","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Doing"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '77f26ada-c58f-5cd9-b754-17ca29a673f6'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Issue Workflow',
  ARRAY['77947897-ec67-5a36-ab7f-72bd34210d1b'::uuid]::uuid[], ARRAY['status']::text[], '{}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

