-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/kanban-professional.agent.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('902e57e9-5552-5823-9206-acbafb1a1b24'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Work Item', '{"titleKey":"title","primaryKey":"id","properties":{"title":{"type":"string","required":true,"displayName":"Title"},"description":{"type":"string","required":false,"displayName":"Description"},"status":{"displayName":"Status","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["To Do","Doing","Done"]}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('8fcb7a2d-03cb-5abb-bdc5-cb21757caacc'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Contact', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"displayName":"Name","type":"string","required":true}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '1065dbf6-baff-528c-8435-e1cf3d0ec136'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Relationship 1', 'ONE_TO_MANY',
  '902e57e9-5552-5823-9206-acbafb1a1b24'::uuid, '8fcb7a2d-03cb-5abb-bdc5-cb21757caacc'::uuid,
  'WorkItem', 'Contact',
  NULL, NULL, NULL, 'assignee', '{"notes":"Assignment of work items to contacts"}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('4772417a-0805-5a1d-beab-fb4bae043265'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Work', '{"executionType":"declarative","parameters":[{"name":"workItem","type":"object-reference","required":true,"displayName":"Work Item","objectTypeId":"902e57e9-5552-5823-9206-acbafb1a1b24"}],"rules":[{"type":"modify_object","properties":{"status":{"value":"Doing","source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"workItem"}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"workItem","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"To Do"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('770bcf64-d1f2-5d13-811f-6ff446f71ad6'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Complete Work', '{"executionType":"declarative","parameters":[{"name":"workItem","type":"object-reference","required":true,"displayName":"Work Item","objectTypeId":"902e57e9-5552-5823-9206-acbafb1a1b24"}],"rules":[{"type":"modify_object","properties":{"status":{"value":"Done","source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"workItem"}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"workItem","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Doing"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('e5f40d1d-2799-58cc-85a5-1fd4202237a2'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Reopen Work', '{"executionType":"declarative","parameters":[{"name":"workItem","type":"object-reference","required":true,"displayName":"Work Item","objectTypeId":"902e57e9-5552-5823-9206-acbafb1a1b24"}],"rules":[{"type":"modify_object","properties":{"status":{"value":"To Do","source":"static"},"lastActivityAt":{"source":"current_timestamp"}},"objectParameter":"workItem"}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"workItem","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Done"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '2a84862b-1a89-52e8-8fc1-99b34313a378'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'WorkItem Workflow',
  ARRAY['902e57e9-5552-5823-9206-acbafb1a1b24'::uuid]::uuid[], ARRAY['status']::text[], '{}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

