-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/kanban-app.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('e7d6b7ba-7219-5ad6-a144-ea41d815c3b6'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Board', '{"titleKey":"name","primaryKey":"id","properties":{"name":{"type":"string","required":true,"displayName":"Board Name"},"description":{"type":"string","required":false,"displayName":"Description"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('564ece16-798e-5e98-9644-2cc44ab96496'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Task', '{"titleKey":"title","primaryKey":"id","properties":{"title":{"type":"string","required":true,"displayName":"Title"},"description":{"type":"string","required":false,"displayName":"Description"},"status":{"type":"string","required":true,"displayName":"Status","picklistConfig":{"options":["Backlog","Todo","In Progress","Review","Done"],"defaultValue":"Backlog","allowMultiple":false}},"priority":{"type":"string","required":false,"displayName":"Priority","picklistConfig":{"options":["Low","Medium","High","Critical"],"defaultValue":"Medium","allowMultiple":false}},"boardId":{"type":"object-reference","required":true,"displayName":"Board","referenceConfig":{"targetObjectTypeId":"e7d6b7ba-7219-5ad6-a144-ea41d815c3b6"}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '1c7d9562-dc12-59f4-8ba0-184bebf7174a'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Board Tasks', 'ONE_TO_MANY',
  'e7d6b7ba-7219-5ad6-a144-ea41d815c3b6'::uuid, '564ece16-798e-5e98-9644-2cc44ab96496'::uuid,
  'board', 'tasks',
  NULL, NULL, NULL, 'boardId', '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('67e3d4af-8188-595c-a747-d9f56d5f7697'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Move to Todo', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"Todo","source":"static"}},"objectParameter":"task"}],"parameters":[{"name":"task","type":"object-reference","required":true,"displayName":"Task","objectTypeId":"564ece16-798e-5e98-9644-2cc44ab96496"}],"executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"task","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Backlog"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('525ee8d0-1f8d-5282-9f5e-df71b1cf832c'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Task', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"In Progress","source":"static"}},"objectParameter":"task"}],"parameters":[{"name":"task","type":"object-reference","required":true,"displayName":"Task","objectTypeId":"564ece16-798e-5e98-9644-2cc44ab96496"}],"executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"task","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Todo"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('868bd3d2-a308-58e7-83c9-a4676bb9db41'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Submit for Review', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"Review","source":"static"}},"objectParameter":"task"}],"parameters":[{"name":"task","type":"object-reference","required":true,"displayName":"Task","objectTypeId":"564ece16-798e-5e98-9644-2cc44ab96496"}],"executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"task","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"In Progress"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('5a1b6655-2c9f-5021-9f86-f0caeebb771d'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Complete Task', '{"rules":[{"type":"modify_object","properties":{"status":{"value":"Done","source":"static"}},"objectParameter":"task"}],"parameters":[{"name":"task","type":"object-reference","required":true,"displayName":"Task","objectTypeId":"564ece16-798e-5e98-9644-2cc44ab96496"}],"executionType":"declarative","submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"task","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Review"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '2e4ca929-3f04-58b0-9534-52300e5d37b8'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Kanban Board',
  ARRAY['564ece16-798e-5e98-9644-2cc44ab96496'::uuid]::uuid[], ARRAY['status']::text[], '{"edges":[],"nodes":[],"version":1}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

