-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/patient-clinic.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Clinic Management', 'clinic')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('e0e66444-e695-5d84-bfc3-6d394c86c504'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Patient', '{"titleKey":"fullName","primaryKey":"id","properties":{"fullName":{"type":"string","required":true,"displayName":"Full Name"},"email":{"type":"string","required":false,"displayName":"Email"},"phone":{"type":"string","required":false,"displayName":"Phone Number"},"dateOfBirth":{"type":"timestamp","required":false,"displayName":"Date of Birth"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('d61a9c1d-69e2-5fcb-83a8-f19c2ae34f76'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Doctor', '{"titleKey":"fullName","primaryKey":"id","properties":{"fullName":{"type":"string","required":true,"displayName":"Full Name"},"specialization":{"type":"string","required":true,"displayName":"Specialization"},"email":{"type":"string","required":false,"displayName":"Email"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('f077a6e6-eb29-52f6-934c-83b082faf342'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Appointment', '{"titleKey":"appointmentTime","primaryKey":"id","properties":{"patientId":{"type":"object-reference","required":true,"displayName":"Patient","referenceConfig":{"targetObjectTypeId":"e0e66444-e695-5d84-bfc3-6d394c86c504"}},"doctorId":{"type":"object-reference","required":true,"displayName":"Doctor","referenceConfig":{"targetObjectTypeId":"d61a9c1d-69e2-5fcb-83a8-f19c2ae34f76"}},"appointmentTime":{"type":"timestamp","required":true,"displayName":"Appointment Time"},"status":{"type":"string","required":true,"displayName":"Status","picklistConfig":{"options":["Scheduled","Checked In","In Consultation","Completed","Cancelled"],"defaultValue":"Scheduled","allowMultiple":false}},"reason":{"type":"string","required":true,"displayName":"Reason for Visit"},"notes":{"type":"string","required":false,"displayName":"Notes"},"vitals":{"type":"string","required":false,"displayName":"Vitals"}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  '5eb667cc-3800-5a12-b1a6-33e0ccec3b09'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Patient Appointments', 'ONE_TO_MANY',
  'e0e66444-e695-5d84-bfc3-6d394c86c504'::uuid, 'f077a6e6-eb29-52f6-934c-83b082faf342'::uuid,
  'patient', 'appointments',
  NULL, NULL, NULL, 'patientId', '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.relationships (
  id, tenant_id, display_name, cardinality,
  source_object_type_id, target_object_type_id,
  source_display_name, target_display_name,
  junction_object_type_id, source_fk_property_name, target_fk_property_name, property_name, config
) VALUES (
  'e598e76a-89ac-5b06-9059-6cdd7028f310'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Doctor Appointments', 'ONE_TO_MANY',
  'd61a9c1d-69e2-5fcb-83a8-f19c2ae34f76'::uuid, 'f077a6e6-eb29-52f6-934c-83b082faf342'::uuid,
  'doctor', 'appointments',
  NULL, NULL, NULL, 'doctorId', '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  cardinality = EXCLUDED.cardinality,
  source_object_type_id = EXCLUDED.source_object_type_id,
  target_object_type_id = EXCLUDED.target_object_type_id,
  source_display_name = EXCLUDED.source_display_name,
  target_display_name = EXCLUDED.target_display_name,
  junction_object_type_id = EXCLUDED.junction_object_type_id,
  source_fk_property_name = EXCLUDED.source_fk_property_name,
  target_fk_property_name = EXCLUDED.target_fk_property_name,
  property_name = EXCLUDED.property_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('6d2b357d-59db-5755-b453-ba481cabf2c8'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Check In Patient', '{"description":"Marks patient as checked in upon arrival","executionType":"declarative","parameters":[{"name":"appointment","type":"object-reference","required":true,"displayName":"Appointment","objectTypeId":"f077a6e6-eb29-52f6-934c-83b082faf342"},{"name":"vitals","type":"string","required":true,"displayName":"Vitals (BP, Temp, etc.)"}],"rules":[{"type":"modify_object","objectParameter":"appointment","properties":{"status":{"value":"Checked In","source":"static"},"vitals":{"source":"parameter","parameterName":"vitals"}}}],"submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"appointment","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Scheduled"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('23305e88-7bd3-5a3b-87c5-bee60bdc166a'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Start Consultation', '{"description":"Doctor starts the consultation","executionType":"declarative","parameters":[{"name":"appointment","type":"object-reference","required":true,"displayName":"Appointment","objectTypeId":"f077a6e6-eb29-52f6-934c-83b082faf342"}],"rules":[{"type":"modify_object","objectParameter":"appointment","properties":{"status":{"value":"In Consultation","source":"static"}}}],"submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"appointment","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Checked In"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('74666c0f-5402-5561-9fdb-c310fe35aecc'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Complete Appointment', '{"description":"Finalize the appointment with notes","executionType":"declarative","parameters":[{"name":"appointment","type":"object-reference","required":true,"displayName":"Appointment","objectTypeId":"f077a6e6-eb29-52f6-934c-83b082faf342"},{"name":"clinicalNotes","type":"string","required":true,"displayName":"Clinical Notes"}],"rules":[{"type":"modify_object","objectParameter":"appointment","properties":{"status":{"value":"Completed","source":"static"},"notes":{"source":"parameter","parameterName":"clinicalNotes"}}}],"submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"appointment","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"In Consultation"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('d438aded-66cc-5c06-b062-f237ee49c6bb'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Cancel Appointment', '{"description":"Cancel the appointment","executionType":"declarative","parameters":[{"name":"appointment","type":"object-reference","required":true,"displayName":"Appointment","objectTypeId":"f077a6e6-eb29-52f6-934c-83b082faf342"},{"name":"reason","type":"string","required":true,"displayName":"Cancellation Reason"}],"rules":[{"type":"modify_object","objectParameter":"appointment","properties":{"status":{"value":"Cancelled","source":"static"},"notes":{"source":"parameter","parameterName":"reason"}}}],"submissionCriteria":[{"left":{"path":{"segments":[],"baseParameterName":"appointment","terminalPropertyKey":"status"},"type":"property"},"type":"comparison","right":{"type":"static","value":"Scheduled"},"operator":"="}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '518bc8b5-bc20-509b-b6e1-8bde797516e3'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Patient Appointment Flow',
  ARRAY['f077a6e6-eb29-52f6-934c-83b082faf342'::uuid]::uuid[], ARRAY['status']::text[], '{"edges":[],"nodes":[],"version":1}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

