-- Generated by tools/metaflow-generator/convert-json-to-sql.mjs
-- Source: examples/metaflow/trello-board.agent.json
BEGIN;

INSERT INTO metaflow.tenants (id, name, slug)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, 'Default Tenant', 'default')
ON CONFLICT (id) DO NOTHING;

INSERT INTO metaflow.object_types (id, tenant_id, display_name, config)
VALUES ('67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal', '{"titleKey":"name","primaryKey":"id","properties":{"status":{"displayName":"Status","type":"string","required":true,"picklistConfig":{"allowMultiple":false,"options":["To Do","Doing","Done"]}},"name":{"displayName":"Deal Name","type":"string","required":true},"amount":{"displayName":"Amount","type":"number","required":false,"validation":{"min":0}}}}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.action_types (id, tenant_id, display_name, config)
VALUES ('4772417a-0805-5a1d-beab-fb4bae043265'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Move to To Do', '{"executionType":"declarative","parameters":[{"name":"deal","type":"object-reference","required":true,"displayName":"Deal","objectTypeId":"67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8"}],"rules":[{"type":"modify_object","properties":{"status":{"value":"To Do","source":"static"}},"objectParameter":"deal"}],"submissionCriteria":[{"type":"comparison","left":{"type":"property","path":{"baseParameterName":"deal","segments":[],"terminalPropertyKey":"status"}},"operator":"=","right":{"type":"static","value":"Done"}}]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  config = EXCLUDED.config,
  updated_at = now();

INSERT INTO metaflow.process_layouts (id, tenant_id, process_name, object_type_ids, tracked_picklists, layout_data)
VALUES (
  '40d127b9-90ad-567c-b2cd-4a6de0bc5afa'::uuid, '00000000-0000-0000-0000-000000000001'::uuid, 'Deal Workflow',
  ARRAY['67c2c3a5-9fb6-53bb-aca5-0a7edde6fbc8'::uuid]::uuid[], ARRAY['status']::text[], '{}'::jsonb
) ON CONFLICT (tenant_id, process_name) DO UPDATE SET
  object_type_ids = EXCLUDED.object_type_ids,
  tracked_picklists = EXCLUDED.tracked_picklists,
  layout_data = EXCLUDED.layout_data,
  updated_at = now();

COMMIT;

